language: cpp
branches:
  only:
    - master
    - /\d+\.\d+\..+/
compiler:
  - gcc
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-pip python-numpy python-yaml python-tk python-colorama python-termcolor python-dev libboost-all-dev libeigen3-dev libqt4-dev libtinyxml-dev cmake git vim net-tools inetutils-ping inetutils-traceroute wget curl
  - sudo pip install --upgrade scikit-learn scipy joblib pandas bs4 matplotlib nose
script:
  - ./bootstrap_bolero.sh
notifications:
  recipients:
    - alexander.fabisch@dfki.de
  email:
    on_success: change
    on_failure: always
