language: cpp
branches:
  only:
    - master
    - /\d+\.\d+\..+/
compiler:
  - gcc
before_script:
  # g++4.8.1
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  # clang 3.4
  - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi
  - sudo apt-get update -qq
  # g++4.8.1
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi
  # clang 3.4
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.4; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.4"; fi
  - sudo apt-get install -qq python-pip python-numpy python-yaml python-dev libboost-all-dev libeigen3-dev libqt4-dev libtinyxml-dev cython pkg-config
  - sudo pip install --upgrade scikit-learn scipy joblib pandas bs4 matplotlib nose
  - wget https://github.com/jbeder/yaml-cpp/archive/release-0.5.3.zip; unzip release-0.5.3.zip; cd yaml-cpp-release-0.5.3/; mkdir build; cd build; cmake -DBUILD_SHARED_LIBS:BOOL=ON ..; sudo make install; cd ../..
script:
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
  - ./bootstrap_bolero.sh
  - ls
  - pwd
  - cd bolero-dev; source env.sh; pybob/pybob.py show-log tools/configmaps
  - cd bolero-dev; source env.sh; pybob/pybob.py show-log learning/bolero/src/representation/dmp
  - cd bolero-dev; source env.sh; pybob/pybob.py show-log learning/bolero/src/environment/cec13_test_functions
  - cd bolero-dev; source env.sh; pybob/pybob.py show-log learning/bolero/src/controller
  - cd bolero-dev; source env.sh; pybob/pybob.py show-log learning/bolero/src/optimizer/cmaes_optimizer
  - cd bolero-dev; source env.sh; pybob/pybob.py show-log learning/bolero/src/environment/mountain_car
  - cd bolero-dev; source env.sh; pybob/pybob.py show-log learning/bolero/src/optimizer/pso_optimizer
  - cd bolero-dev; source env.sh; pybob/pybob.py show-log learning/bolero/src/environment/function_approximation
  - cd bolero-dev; source env.sh; pybob/pybob.py show-log learning/bolero
notifications:
  recipients:
    - alexander.fabisch@dfki.de
  email:
    on_success: change
    on_failure: always
