language: cpp
branches:
  only:
    - master
    - /\d+\.\d+\..+/
compiler:
  - gcc
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-pip python-numpy python-yaml python-dev libboost-all-dev libeigen3-dev libqt4-dev libtinyxml-dev cython
  - sudo pip install --upgrade scikit-learn scipy joblib pandas bs4 matplotlib nose
  - wget https://github.com/jbeder/yaml-cpp/archive/release-0.5.3.zip; unzip release-0.5.3.zip; cd yaml-cpp-release-0.5.3/; mkdir build; cd build; cmake -DBUILD_SHARED_LIBS:BOOL=ON ..; sudo make install; cd ../..
script:
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
  - ./bootstrap_bolero.sh
notifications:
  recipients:
    - alexander.fabisch@dfki.de
  email:
    on_success: change
    on_failure: always
