language: cpp
compiler: gcc
dist: trusty
branches:
  only:
    - master
    - /\d+\.\d+\..+/
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-dev python-pip python-numpy python-tk libboost-all-dev libeigen3-dev libqt4-dev libtinyxml-dev cython pkg-config libyaml-cpp-dev
  - sudo pip install pyyaml scikit-learn scipy joblib pandas bs4 matplotlib nose scikit-optimize gym
  - export PYTHONPATH=$PYTHONPATH:/usr/lib/python2.7/dist-packages
script:
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
  - ./bootstrap_bolero.sh
  - cd bolero-dev; source env.sh; cd learning/bolero; nosetests -sv
  # uncomment to debug failing builds:
  #- cd bolero-dev; source env.sh; pybob/pybob.py show-log <package>
  - cat autoproj/bob/logs/*.txt
  - source env.sh; pypob/pybob.py show-log learning/bolero/src/representation/dmp
notifications:
  recipients:
    - alexander.fabisch@dfki.de
  email:
    on_success: change
    on_failure: always
