version: 2
jobs:
  build:
    docker:
      - image: af01/bolero_dependencies:latest
    steps:
      - checkout
      - run:
          name: Build
          command: ./bootstrap_bolero.sh
      - run:
          name: Test
          command: cd bolero-dev; source env.sh; cd learning/bolero/; nosetests bolero -sv
