version: 2
general:
  build_dir: build
  branches:
    ignore:
      - gh-pages
jobs:
  build:
    docker:
      - image: af01/bolero_dependencies:latest
    steps:
      - checkout
      - run:
          name: Build
          command: .circleci/build.sh
      - run:
          name: Test
          command: .circleci/test.sh
      - run:
          name: Deploy
          command: cp -R $CIRCLE_WORKING_DIRECTORY/bolero-dev $CIRCLE_ARTIFACTS
